### ISSUE TITLE
Is this of any use for divestos?

### ISSUE THREAD

**Issue by ghost** [Divested-Mobile/Extirpater#1]
If DivestOs has encryption and uses cryptoshredding, surely this isn not needed for modern android versions.

**Comment by SkewedZeppelin** [comment]
> Use before selling your device, after enabling encryption, or after deleting many apps/files.

Just because a file system is encrypted, doesn't mean files cannot be recovered.

Might be a more complicated/impossible with file based encryption, but still useful on block based encryption.
