### ISSUE TITLE
[Documentation] Change the description of the application to be more explicit

### ISSUE THREAD

**Issue by Moonstone3010** [Divested-Mobile/Extirpater#4]
When installing an application from [DivestOS Official F-Droid repo](https://divestos.org/fdroid/official/), there is no information about what the application is doing (clearing free space).

In addition, the term `free space eraser` can be confusing, because it is not known whether the word `free` refers to the storage space or the application itself. One might think that the application is free (because it is) and it overwrites all memory including existing files.

Apart from installing and running the application, it is still unknown what it actually does. Instead of `Start` on the button, maybe it would be better to put `Clear Free Space` or `Overwrite Free Space` there.  Also, at some point there should be a warning that deleting may take some time and not to interrupt it (if it can be in any way harmful to the device's memory).

**Comment by SkewedZeppelin** [comment]
Doesn't the description already explain this?

https://github.com/Divested-Mobile/Extirpater/blob/master/fastlane/metadata/android/en-US/full_description.txt

**Comment by Moonstone3010** [comment]
> Doesn't the description already explain this?

Well, the term `free space eraser` is enough for me, but if you want the average user to know what this application is for, I think you need to use simple and direct terms like:
 - This app overwrites free space in your device's memory
 - This app will not delete your files or any data currently on your device


> https://github.com/Divested-Mobile/Extirpater/blob/master/fastlane/metadata/android/en-US/full_description.txt

The description of the application in the DivestOS repo ends on the 4th line.  There is a longer one in the main F-Droid repository.

**Comment by SkewedZeppelin** [comment]
> The description of the application in the DivestOS repo ends on the 4th line. There is a longer one in the main F-Droid repository.

What client are you using? The description provided by F-Droid pulled from fastlane should override the one in the DivestOS repository.

**Comment by Moonstone3010** [comment]
Yes I know.  But it works exactly the opposite.  When both repos are enabled, the description from the DivestOS repo appears in the application and in the Versions section there is no option to choose which repository I want to install the apk from.
I am using the official F-Droid application in the latest available version.
