### ISSUE TITLE
Add DOD wipe patterns (5220.22-M and 5220.22-M ECE).

### ISSUE THREAD

**Issue by nl255** [Divested-Mobile/Extirpater#5]
Please consider adding the DOD/NIST standard wipe patterns which use multiple overwrites in specific patterns to help ensure full erasure.

Standard 5220.22-M:
Pass 1: Writes a zero and verifies the write.
Pass 2: Writes a one and verifies the write.
Pass 3: Writes a random character and verifies the write. 

5220.22-M ECE runs DoD 5220.22-M twice, and an additional pass (DoD 5220.22-M (C) Standard) in between.

**Comment by SkewedZeppelin** [comment]
no, this isn't a hard drive
full erasure cannot be achieved regardless.
